[package]
name = "polkadot-rewards"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
argh = "0.1.4"
chrono = "0.4.19"
csv = "1.1.5"
env_logger = "0.8.3"
miniserde = "0.1.13"
ureq = "2.0"
json = "0.12"
